# Generated by Django 2.0.6 on 2018-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='URLimagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
