# Generated by Django 2.0.6 on 2018-06-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180603_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.CharField(choices=[('0', 'Deportes'), ('1', 'Ocio'), ('2', 'Tecnologia'), ('3', 'Salud'), ('4', 'Naturaleza')], max_length=1),
        ),
    ]
