# Generated by Django 2.0.6 on 2018-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('ads', '0005_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='categorias.Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fechapublicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
